name: user
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: 2.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^2.3.1
  pageview_indicator_plugins: ^0.0.2
  scoped_model: ^1.0.1
  dio: ^3.0.10
  time_picker_widget: ^1.0.0+10
  shared_preferences: ^2.0.5
  connectivity: ^3.0.6
  path_provider: ^2.0.1
  intl: ^0.17.0
  #flushbar: ^1.10.0
  another_flushbar: ^1.10.23
  dropdown_search: ^0.6.3
  #dropdown_search: ^0.6.3
  rflutter_alert: ^1.1.0
  file_picker:
  image_picker: ^0.6.5+2
  date_format: ^2.0.2
  convex_bottom_bar: ^2.7.1
  percent_indicator: "^2.1.7+2"
  syncfusion_flutter_calendar: ^19.1.67
  otp_text_field: ^1.1.1
  flutter_toggle_tab: ^1.1.4
  url_launcher: ^6.0.9
  intro_slider: ^3.0.2
  flutter_webview_plugin: ^0.4.0
  #webview_flutter: ^2.0.12
  unique_identifier: ^0.2.0
  lottie: ^1.1.0
  #video_player: ^2.1.13
  #table_calendar: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/i18n/
    - assets/images/
    - assets/intro/

  fonts:

    - family:  Monte
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

    - family:  MonteMed
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family:  DINLight
      fonts:
        - asset: fonts/DINNextLTPro-Light.otf

    - family:  DINBold
      fonts:
        - asset: fonts/DINNextLTPro-Bold.otf

    - family:  DINMed
      fonts:
        - asset: fonts/DINNextLTPro-Medium.otf

    - family:  DINReg
      fonts:
        - asset: fonts/DINNextLTPro-Regular.otf

